### ISSUE TITLE
 Using Installer: unrecognized arguments: --zluda

### ISSUE THREAD

**Issue by AndyH3H1** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#14]
Hello all,
I didn´t find a similar problem, so I created this new issue.
I have already installed stable-diffusion-webui-amdgpu, so for the first try I wanted to use the installer to check, if it works easy for me.
I downloaded https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z as described. After uncompressing I used update.bat and after that I added --zluda to the webui-user.bat in webui folder:

----------------------------
webui-user.bat:
----------------------------
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--zluda

@REM Uncomment following code to reference an existing A1111 checkout.
@REM set A1111_HOME=Your A1111 checkout dir
@REM
@REM set VENV_DIR=%A1111_HOME%/venv
@REM set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
@REM  --ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
@REM  --hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
@REM  --embeddings-dir %A1111_HOME%/embeddings ^
@REM  --lora-dir %A1111_HOME%/models/Lora

call webui.bat
----------------------------

After that I start it with run.bat:

----------------------------

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-250-g3589b57e
Commit hash: 3589b57ec1f59fd7c570b08c85e0108cf3ff67d6
Launching Web UI with arguments: --zluda
Total VRAM 16368 MB, total RAM 16303 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7800 XT [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
D:\AI\SDZluda\stable-diffusion-webui-amdgpu-forge\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
usage: launch.py [-h] [--gpu-device-id DEVICE_ID] [--all-in-fp32 | --all-in-fp16]
                 [--unet-in-bf16 | --unet-in-fp16 | --unet-in-fp8-e4m3fn | --unet-in-fp8-e5m2]
                 [--vae-in-fp16 | --vae-in-fp32 | --vae-in-bf16] [--vae-in-cpu]
                 [--clip-in-fp8-e4m3fn | --clip-in-fp8-e5m2 | --clip-in-fp16 | --clip-in-fp32]
                 [--attention-split | --attention-quad | --attention-pytorch]
                 [--force-upcast-attention | --disable-attention-upcast] [--disable-xformers]
                 [--directml [DIRECTML_DEVICE]] [--disable-ipex-hijack]
                 [--always-gpu | --always-high-vram | --always-normal-vram | --always-low-vram | --always-no-vram | --always-cpu]
                 [--always-offload-from-vram] [--pytorch-deterministic] [--cuda-malloc] [--cuda-stream]
                 [--pin-shared-memory] [--update-all-extensions] [--skip-python-version-check]
                 [--skip-torch-cuda-test] [--reinstall-xformers] [--reinstall-torch] [--update-check] [--test-server]
                 [--log-startup] [--skip-prepare-environment] [--skip-install] [--dump-sysinfo] [--loglevel LOGLEVEL]
                 [--do-not-download-clip] [--data-dir DATA_DIR] [--models-dir MODELS_DIR] [--config CONFIG]
                 [--ckpt CKPT] [--ckpt-dir CKPT_DIR] [--vae-dir VAE_DIR] [--gfpgan-dir GFPGAN_DIR]
                 [--gfpgan-model GFPGAN_MODEL] [--no-half] [--no-half-vae] [--no-progressbar-hiding]
                 [--max-batch-count MAX_BATCH_COUNT] [--embeddings-dir EMBEDDINGS_DIR]
                 [--textual-inversion-templates-dir TEXTUAL_INVERSION_TEMPLATES_DIR]
                 [--hypernetwork-dir HYPERNETWORK_DIR] [--localizations-dir LOCALIZATIONS_DIR] [--allow-code]
                 [--medvram] [--medvram-sdxl] [--lowvram] [--lowram] [--always-batch-cond-uncond] [--unload-gfpgan]
                 [--precision {full,half,autocast}] [--upcast-sampling] [--share] [--ngrok NGROK]
                 [--ngrok-region NGROK_REGION] [--ngrok-options NGROK_OPTIONS] [--enable-insecure-extension-access]
                 [--codeformer-models-path CODEFORMER_MODELS_PATH] [--gfpgan-models-path GFPGAN_MODELS_PATH]
                 [--esrgan-models-path ESRGAN_MODELS_PATH] [--bsrgan-models-path BSRGAN_MODELS_PATH]
                 [--realesrgan-models-path REALESRGAN_MODELS_PATH] [--dat-models-path DAT_MODELS_PATH]
                 [--clip-models-path CLIP_MODELS_PATH] [--xformers] [--force-enable-xformers]
                 [--xformers-flash-attention] [--deepdanbooru] [--opt-split-attention] [--opt-sub-quad-attention]
                 [--sub-quad-q-chunk-size SUB_QUAD_Q_CHUNK_SIZE] [--sub-quad-kv-chunk-size SUB_QUAD_KV_CHUNK_SIZE]
                 [--sub-quad-chunk-threshold SUB_QUAD_CHUNK_THRESHOLD] [--opt-split-attention-invokeai]
                 [--opt-split-attention-v1] [--opt-sdp-attention] [--opt-sdp-no-mem-attention]
                 [--disable-opt-split-attention] [--disable-nan-check] [--use-cpu USE_CPU [USE_CPU ...]] [--use-ipex]
                 [--disable-model-loading-ram-optimization] [--listen] [--port PORT] [--show-negative-prompt]
                 [--ui-config-file UI_CONFIG_FILE] [--hide-ui-dir-config] [--freeze-settings]
                 [--freeze-settings-in-sections FREEZE_SETTINGS_IN_SECTIONS]
                 [--freeze-specific-settings FREEZE_SPECIFIC_SETTINGS] [--ui-settings-file UI_SETTINGS_FILE]
                 [--gradio-debug] [--gradio-auth GRADIO_AUTH] [--gradio-auth-path GRADIO_AUTH_PATH]
                 [--gradio-img2img-tool GRADIO_IMG2IMG_TOOL] [--gradio-inpaint-tool GRADIO_INPAINT_TOOL]
                 [--gradio-allowed-path GRADIO_ALLOWED_PATH] [--opt-channelslast] [--styles-file STYLES_FILE]
                 [--autolaunch] [--theme THEME] [--use-textbox-seed] [--disable-console-progressbars]
                 [--enable-console-prompts] [--vae-path VAE_PATH] [--disable-safe-unpickle] [--api]
                 [--api-auth API_AUTH] [--api-log] [--nowebui] [--ui-debug-mode] [--device-id DEVICE_ID]
                 [--administrator] [--cors-allow-origins CORS_ALLOW_ORIGINS]
                 [--cors-allow-origins-regex CORS_ALLOW_ORIGINS_REGEX] [--tls-keyfile TLS_KEYFILE]
                 [--tls-certfile TLS_CERTFILE] [--disable-tls-verify] [--server-name SERVER_NAME] [--gradio-queue]
                 [--no-gradio-queue] [--skip-version-check] [--no-hashing] [--no-download-sd-model]
                 [--subpath SUBPATH] [--add-stop-route] [--api-server-stop] [--timeout-keep-alive TIMEOUT_KEEP_ALIVE]
                 [--disable-all-extensions] [--disable-extra-extensions] [--skip-load-model-at-start]
                 [--unix-filenames-sanitization] [--filenames-max-length FILENAMES_MAX_LENGTH] [--no-prompt-history]
                 [--forge-ref-a1111-home FORGE_REF_A1111_HOME] [--controlnet-dir CONTROLNET_DIR]
                 [--controlnet-preprocessor-models-dir CONTROLNET_PREPROCESSOR_MODELS_DIR]
                 [--scunet-models-path SCUNET_MODELS_PATH] [--swinir-models-path SWINIR_MODELS_PATH]
                 [--controlnet-loglevel {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--controlnet-tracemalloc]
                 [--lora-dir LORA_DIR] [--lyco-dir-backcompat LYCO_DIR_BACKCOMPAT]
launch.py: error: unrecognized arguments:--zluda

----------------------------

Did I miss something? Or do I have to set something up?

I tried --use-zluda like in stable-diffusion-webui-amdgpu, but the same problem happens.

I tried installing via git, but I got a lot of errors. I have to check this. It´s maybe because of the existing stable-diffusion-webui-amdgpu, so I first wanted to try the Installer where everything is included.

Thank you and best regards,
Andy

**Comment by lshqqytiger** [comment]
One-Click package is not supported. You have to clone from GitHub using Git.

**Comment by AndyH3H1** [comment]
Thank you for the very quick reply.

I think I missunderstood the installation guide:

---------------

Or you can just use this one-click installation package (with git and python included).

[>>> Click Here to Download One-Click Package (CUDA 12.1 + Pytorch 2.3.1) <<<](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z)


After you download, you uncompress, use update.bat to update, and use run.bat to run.

Note that running update.bat is important, otherwise you may be using a previous version with potential bugs unfixed.

---------------

In which case I can use this method? Is it only usable if I already has forge installed in an older version?

**Comment by AndyH3H1** [comment]
I got the git way work.
Thank you for the help and your work!
