### ISSUE TITLE
[BUG] LORA image degradation

### ISSUE THREAD

**Issue by TheFerumn** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#17]
After last update i can't really use any lora because every next generated image is drastically worse than previous. Doesn't matter if i generate in batch or 1 by 1. When i switch checkpoint it will generate like 1 or 2 images with good quality and i have to switch checkpoint again. I am using DirectML and it only happenes when using any lora. I also disabled every commands and left --directml only.
For example i generated 5 images with a Detail Tweaker LoRA
![grid-0017](https://github.com/user-attachments/assets/4159e0e5-5dda-46af-87ad-828936fb5853)
Then another 5:
![grid-0018](https://github.com/user-attachments/assets/b106a844-9662-401f-8bd5-238937f9f9b2)
Other LORAs are even way worse than this.

**Comment by Grey3016** [comment]
Issue with the Loras not Forge.

**Comment by TheFerumn** [comment]
fixed after last update
