### ISSUE TITLE
[Bug]: Getting Import Error While Accessing pydantic.fields

### ISSUE THREAD

**Issue by Juelsman3343** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#2]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I clone a fresh install of amdgpu-forge and the UI fails to run after a second startup. It gives me an error message `ImportError: cannot import name 'Undefined' from 'pydantic.fields'` and a traceback. I can run StableDiffusion so long as I don't shut down Forge and try to reopen it. But I'd rather not reinstall Forge every time I want to use it again. Running on GPU RX6600XT.

### Steps to reproduce the problem

1. Install Fresh Version of Forge
2. Run webui-user.bat (using --zluda argument)
3. Wait for installation of venv folder.
4. Forge opens and runs properly
5. Close Forge
6. run webui-user.bat (using --zluda argument)
7. Receive error message.

### What should have happened?

Forge should have opened on its own. As far as I can tell, I can install it, run it once right off the install and then never again.

### What browsers do you use to access the UI ?

Brave, Other

### Sysinfo

[sysinfo.json](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/files/15257107/sysinfo.json)

### Console logs

```Shell
`venv ".\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File ".\launch.py", line 51, in <module>
    main()
  File ".\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File ".\modules\launch_utils.py", line 664, in dump_sysinfo
    from modules import sysinfo
  File ".\modules\sysinfo.py", line 12, in <module>
    from modules import paths_internal, timer, shared, extensions, errors, devices
  File ".\modules\shared.py", line 4, in <module>
    import gradio as gr
  File ".\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File ".\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File ".\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "D:\AIApps\SDForge\stable-diffusion-webui-amdgpu-forge(old)\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File ".\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File ".\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File ".\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File ".\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (.\venv\lib\site-packages\pydantic\fields.py)
Press any key to continue . . .`
```

### Additional information

I've found using the AMD Adrenaline software works on my PC for ROCM. If I use The PRO version ROCM crashes for a modified AMDWebUI which has been modified to run ZLUDA. I can run AMDWebUI with ROCM and ZLUDA just fine. Also, I am using this on my D: drive, but I don't believe that should have any affect.

**Comment by brknsoul** [comment]
Insightface causes a too-new version of a couple of modules to be installed. We'll roll them back.

Open command prompt in stable-diffusion-webui-amdgpu-forge  folder

run these command one after the other;
```
venv\Scripts\activate
pip install insightface
pip install albumentations==1.4.3
pip install pydantic==1.10.15
```

**Comment by Juelsman3343** [comment]
> Insightface causes a too-new version of a couple of modules to be installed. We'll roll them back.
> 
> Open command prompt in `stable-diffusion-webui-amdgpu-forge` folder
> 
> run these command one after the other;
> 
> ```
> venv\Scripts\activate
> pip install insightface
> pip install albumentations==1.4.3
> pip install pydantic==1.10.15
> ```

Thanks for the tip, but I think it's not up to date. There's another commit (There were 5 when I posted this, now there's 6) and it's still failing for me. I'm getting a new error now:
`venv ".\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-1.7.0
Commit hash: e45bfd91b123559e69b5bfca3824df15735a0b95
Using ZLUDA in .\.zluda
Total VRAM 8176 MB, total RAM 65458 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 XT [ZLUDA] : native
VAE dtype: torch.bfloat16
Launching Web UI with arguments: --zluda --theme dark
CUDA Stream Activated:  False

------------------------------------------------------------------------------------------------------------------------
launch.py 51 <module>
main()

launch.py 47 main
start()

launch_utils.py 651 start
import webui

webui.py 19 <module>
initialize.imports()

initialize.py 50 imports
shared_init.initialize()

shared_init.py 63 initialize
from modules.onnx_impl import initialize as initialize_onnx

ImportError:
cannot import name 'initialize' from 'modules.onnx_impl' (.\modules\onnx_impl\__init__.py)
Press any key to continue . . .`

**Comment by DeeiaaN** [comment]
@Juelsman3343 
I fixed this error with changing line 63 and  deleting line 64 in modules/shared_init.py:

`    if not cmd_opts.skip_ort:
        from modules.onnx_impl import initialize_onnx

    initialize_zluda()`

**Comment by pinea00** [comment]
The same problem also occurred when I updated the code ~ I can only wait for the author to correct it

**Comment by pIuraI** [comment]
Same issue for me on the latest

**Comment by wtnwin** [comment]
Same issue for me

**Comment by pinea00** [comment]
Set up VENV manually before starting the installation
python -m SD-forge directory\venv
Then
venv\Scripts\activate
pip install torch==2.2.2 torchvision --index-url https://download.pytorch.org/whl/cu118

You can also reinstall torch after installation is complete.
pip uninstall torch
pip install torch==2.2.2 torchvision --index-url https://download.pytorch.org/whl/cu118

Because the latest version of torch2.3 is incompatible with SD

**Comment by Fentskii** [comment]
> Insightface causes a too-new version of a couple of modules to be installed. We'll roll them back.
> 
> Open command prompt in `stable-diffusion-webui-amdgpu-forge` folder
> 
> run these command one after the other;
> 
> ```
> venv\Scripts\activate
> pip install insightface
> pip install albumentations==1.4.3
> pip install pydantic==1.10.15
> ```

I was facing this bug on the latest version, but attempting your fix worked for me, much appreciated!
