### ISSUE TITLE
ModuleNotFoundError: No module named 'gguf'

### ISSUE THREAD

**Issue by hreessffgg** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#25]
C:\stable-diffusion-webui-amdgpu-forge-main>webui-user
venv "C:\stable-diffusion-webui-amdgpu-forge-main\venv\Scripts\Python.exe"
ROCm Toolkit 6.1 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 9aae0058477ecc1e51f62399f7b4558090289bc2
Using ZLUDA in C:\stable-diffusion-webui-amdgpu-forge-main\.zluda
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-amdgpu-forge-main\launch.py", line 54, in <module>
    main()
  File "C:\stable-diffusion-webui-amdgpu-forge-main\launch.py", line 42, in main
    prepare_environment()
  File "C:\stable-diffusion-webui-amdgpu-forge-main\modules\launch_utils.py", line 608, in prepare_environment
    from modules import devices
  File "C:\stable-diffusion-webui-amdgpu-forge-main\modules\devices.py", line 3, in <module>
    from backend import memory_management
  File "C:\stable-diffusion-webui-amdgpu-forge-main\backend\memory_management.py", line 10, in <module>
    from backend import stream, utils
  File "C:\stable-diffusion-webui-amdgpu-forge-main\backend\utils.py", line 1, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'
Press any key to continue . . .

Hello, I receive the above error after launching webui-user and substantial content downloads and installs. Thoughts on how to resolve?

**Comment by TheFerumn** [comment]
Here is the link how i fixed it
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/24

**Comment by thomashush** [comment]
I have this same error. The solution in #24 didn't help or solve my issue.

venv "E:\automatic_forge\venv\Scripts\Python.exe"
ROCm Toolkit 5.7 was found.
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 9aae0058477ecc1e51f62399f7b4558090289bc2
Using ZLUDA in E:\automatic_forge\.zluda
You are up to date with the most recent release.
Traceback (most recent call last):
  File "E:\automatic_forge\launch.py", line 57, in <module>
    main()
  File "E:\automatic_forge\launch.py", line 45, in main
    prepare_environment()
  File "E:\automatic_forge\modules\launch_utils.py", line 608, in prepare_environment
    from modules import devices
  File "E:\automatic_forge\modules\devices.py", line 3, in <module>
    from backend import memory_management
  File "E:\automatic_forge\backend\memory_management.py", line 10, in <module>
    from backend import stream, utils
  File "E:\automatic_forge\backend\utils.py", line 1, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'
Press any key to continue . . .

**Comment by TheFerumn** [comment]
> I have this same error. The solution in #24 didn't help or solve my issue.

You sure you added it correctly ?
Module gguf is already built in this version but its in the folder which Stable Diffusion doesn't check for some reason.
![image](https://github.com/user-attachments/assets/8256303e-57c5-45e0-b27d-4191a02659ec)
This is how i edited it.
Ignore other logging edits since i added it just to make log files.

**Comment by thomashush** [comment]
> > I have this same error. The solution in #24 didn't help or solve my issue.
> 
> You sure you added it correctly ? Module gguf is already built in this version but its in the folder which Stable Diffusion doesn't check for some reason. ![image](https://private-user-images.githubusercontent.com/178197881/363796655-8256303e-57c5-45e0-b27d-4191a02659ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTg0NTcsIm5iZiI6MTcyNTMxODE1NywicGF0aCI6Ii8xNzgxOTc4ODEvMzYzNzk2NjU1LTgyNTYzMDNlLTU3YzUtNDVlMC1iMjdkLTQxOTFhMDI2NTllYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQyMzAyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTQyODFhOGVmZGY3ODYzYzc4OTdiMjdkMTc3Y2YzZDllNzNhOTVkOWYyZDMxYjU2ODlkOGQ3MTMxMjBmZTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CL3JXEWQqCG9ZmhoiHK2Q5m6aaUwumWj47yUMVbBsPg) This is how i edited it. Ignore other logging edits since i added it just to make log files.
> 
> I don't have to add the fact that you have to edit path to your packages_3rdparty folder ? Its obvious right ?

I got it, I forgot that I had to swap the slashes. 

import sys
sys.path.append("E:/automatic_forge/packages_3rdparty")

**Comment by lshqqytiger** [comment]
Fixed. Please discard changes and pull the latest commits.
```
git restore .
git pull
```
