### ISSUE TITLE
ONNX and Protobuf requirement

### ISSUE THREAD

**Issue by TheFerumn** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#30]
```
Collecting onnx>=1.14.0
  Using cached onnx-1.16.2-cp310-cp310-win_amd64.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.20 in c:\stable diffusion\new-forge\venv\lib\site-packages (from onnx>=1.14.0) (1.26.2)
Requirement already satisfied: protobuf>=3.20.2 in c:\stable diffusion\new-forge\venv\lib\site-packages (from onnx>=1.14.0) (4.25.4)
Using cached onnx-1.16.2-cp310-cp310-win_amd64.whl (14.4 MB)
Installing collected packages: onnx
  Attempting uninstall: onnx
    Found existing installation: onnx 1.12.0
    Uninstalling onnx-1.12.0:
      Successfully uninstalled onnx-1.12.0
Successfully installed onnx-1.16.2
Error: (onnx 1.12.0 (c:\stable diffusion\new-forge\venv\lib\site-packages), Requirement.parse('onnx>=1.14.0'))
```

I have this issue maybe for 2 months already. I can use SD but it kind of making me annoyed. Everytime i launch SD i have this sequence of installing onnx and protobuf and i am not sure which versions a should actually use. So requirements_versions.txt shows i need to use protobuf 3.20.0, there is nothing about onnx version. Compatible onnx version for protobuf 3.20.0 should be 1.12.0 but it installs newer version and after using pipdeptree i see this: 

```
Warning!!! Possibly conflicting dependencies found:
* mediapipe==0.10.14
 - protobuf [required: >=4.25.3,<5, installed: 5.28.1]
* olive-ai==0.6.2
 - protobuf [required: <4.0.0, installed: 5.28.1]
* open-clip-torch==2.20.0
 - protobuf [required: <4, installed: 5.28.1]
```
mediapipe is installed by forge_legacy_preprocessors extension

I tried to set onnx to 1.12.0 in requirements_versions.txt but it gets ignored probably because newer version of protobuf is also installed. Any idea how to fix this ? Or should i just delete version of protobuf in requirements_versions.txt and just use 5.28.1 as it forces ?

**Comment by KungFuFurniture** [comment]
Fyi I get this too when trying to use the Swap extensions you were helping me with.

**Comment by TheFerumn** [comment]
Fixed after last requirements_versions.txt update
