### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by depeschzeu** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#37]
Try to start it on my AMD and get this on first start

```
Traceback (most recent call last):
  File "C:\stabdif\stable-diffusion-webui-amdgpu-forge\launch.py", line 54, in <module>
    main()
  File "C:\stabdif\stable-diffusion-webui-amdgpu-forge\launch.py", line 42, in main
    prepare_environment()
  File "C:\stabdif\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 525, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA!
```

Is there a way to fix this?

**Comment by lshqqytiger** [comment]
need more details. command line arguments, environment, device and full log.

**Comment by Richthegit** [comment]
So, follow this guide https://github.com/patientx/ComfyUI-Zluda. Now copy the venv and zluda folders from the comfyui-zluda folder,  into this repo cloned folder (before installing this repo). Now edit the webui-user.bat like this: 
@echo off

set PYTHON="%~dp0/venv/Scripts/python.exe"
set GIT=
set VENV_DIR=./venv
set COMMANDLINE_ARGS=--use-zluda
set ZLUDA_COMGR_LOG_LEVEL=1

@REM Uncomment following code to reference an existing A1111 checkout.
@REM set A1111_HOME=Your A1111 checkout dir
@REM
@REM set VENV_DIR=%A1111_HOME%/venv
@REM set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
@REM  --ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
@REM  --hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
@REM  --embeddings-dir %A1111_HOME%/embeddings ^
@REM  --lora-dir %A1111_HOME%/models/Lora

call webui.bat
........................ Now run webui-user.bat.

This worked for my RX 6600 on Win 10.
