### ISSUE TITLE
[Bug]: can not install it

### ISSUE THREAD

**Issue by waldolin** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#4]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

1.
git clone  https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge
a new file
2.
set webui-user.bat
---
set PYTHON=C:\Users\lin\stable-diffusion-webui-directml\python\python.exe
set GIT=
set VENV_DIR=
set A1111_HOME=D:\Users\lin\stable-diffusion-webui-directml\
set COMMANDLINE_ARGS=--skip-torch-cuda-test --use-directml --medvram --precision full --no-half --no-half-vae --opt-sub-quad-attention --enable-insecure-extension-access --deepdanbooru --disable-nan-check 
--ckpt-dir D:\Users\lin\stable-diffusion-webui-directml/models/Stable-diffusion 
--hypernetwork-dir D:\Users\lin\stable-diffusion-webui-directml/models/hypernetworks 
--embeddings-dir D:\Users\lin\stable-diffusion-webui-directml/embeddings 
--lora-dir D:\Users\lin\stable-diffusion-webui-directml/models/Lora
rem --onnx
set SAFETENSORS_FAST_GPU=1
----
3. open it to first time installation.

----
'--ckpt-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--hypernetwork-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--embeddings-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--lora-dir' 不是內部或外部命令、可執行的程式或批次檔。
'et' 不是內部或外部命令、可執行的程式或批次檔。
Creating venv in directory D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv using python "C:\Users\lin\stable-diffusion-webui-directml\python\python.exe"
venv "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-1.7.0
Commit hash: e45bfd91b123559e69b5bfca3824df15735a0b95
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.3.0
  Downloading https://download.pytorch.org/whl/cu121/torch-2.3.0%2Bcu121-cp310-cp310-win_amd64.whl (2413.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 GB 640.0 kB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.18.0%2Bcu121-cp310-cp310-win_amd64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 2.2 MB/s eta 0:00:00
Collecting filelock
  Using cached filelock-3.14.0-py3-none-any.whl (12 kB)
Collecting jinja2
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting fsspec
  Using cached fsspec-2024.3.1-py3-none-any.whl (171 kB)
Collecting networkx
  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting typing-extensions>=4.8.0
  Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting mkl<=2021.4.0,>=2021.1.1
  Downloading https://download.pytorch.org/whl/mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.5/228.5 MB 4.4 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Using cached pillow-10.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting intel-openmp==2021.*
  Downloading https://download.pytorch.org/whl/intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 3.0 MB/s eta 0:00:00
Collecting tbb==2021.*
  Using cached tbb-2021.12.0-py3-none-win_amd64.whl (286 kB)
Collecting MarkupSafe>=2.0
  Downloading https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: tbb, mpmath, intel-openmp, typing-extensions, sympy, pillow, numpy, networkx, mkl, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.5 filelock-3.14.0 fsspec-2024.3.1 intel-openmp-2021.4.0 jinja2-3.1.4 mkl-2021.4.0 mpmath-1.3.0 networkx-3.3 numpy-1.26.4 pillow-10.3.0 sympy-1.12 tbb-2021.12.0 torch-2.3.0+cu121 torchvision-0.18.0+cu121 typing-extensions-4.11.0

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv\Scripts\python.exe -m pip install --upgrade pip
Installing clip
Installing open_clip
Installing requirements
Installing forge_legacy_preprocessor requirement: fvcore
Installing forge_legacy_preprocessor requirement: mediapipe
Installing forge_legacy_preprocessor requirement: svglib
Installing forge_legacy_preprocessor requirement: insightface
Installing forge_legacy_preprocessor requirement: handrefinerportable
Installing forge_legacy_preprocessor requirement: depth_anything
Traceback (most recent call last):
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\launch.py", line 51, in <module>
    main()
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\launch.py", line 39, in main
    prepare_environment()
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 600, in prepare_environment
    from modules import devices
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\modules\devices.py", line 3, in <module>
    import ldm_patched.modules.model_management as model_management
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\ldm_patched\modules\model_management.py", line 122, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\ldm_patched\modules\model_management.py", line 91, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
請按任意鍵繼續 . . .

open again
'--ckpt-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--hypernetwork-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--embeddings-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--lora-dir' 不是內部或外部命令、可執行的程式或批次檔。
'et' 不是內部或外部命令、可執行的程式或批次檔。
venv "D:\Users\lin\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-1.7.0
Commit hash: e45bfd91b123559e69b5bfca3824df15735a0b95
Cloning assets into D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\stable-diffusion-webui-assets...
Cloning into 'D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\stable-diffusion-webui-assets'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
Receiving objects: 100% (20/20), 132.70 KiB | 325.00 KiB/s, done.

Cloning Stable Diffusion into D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\stable-diffusion-stability-ai...
Cloning into 'D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (571/571), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 580 (delta 278), reused 446 (delta 247), pack-reused 9Receiving objects:  92% (534/580), 73.00 MiB | 3.83

Resolving deltas: 100% (278/278), done.
Cloning Stable Diffusion XL into D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\generative-models...
Cloning into 'D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\generative-models'...
remote: Enumerating objects: 941, done.
remote: Total 941 (delta 0), reused 0 (delta 0), pack-reused 941Receiving objects:  45% (424/941), 43.11 MiB | 4.26 MiB/Receiving objects:  47% (443/941), 43.11 MiB | 4.26 MiB/s
Receiving objects: 100% (941/941), 43.85 MiB | 4.03 MiB/s, done.
Resolving deltas: 100% (491/491), done.
Cloning K-diffusion into D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\k-diffusion...
Cloning into 'D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\k-diffusion'...
remote: Enumerating objects: 1345, done.
remote: Counting objects: 100% (743/743), done.
remote: Compressing objects: 100% (94/94), done.
Receiving objects: 100% (1345/1345), 236.07 KiB | 857.00 KiB/s, done.02Receiving objects:  99% (1332/1345)

Resolving deltas: 100% (945/945), done.
Cloning BLIP into D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\BLIP...
Cloning into 'D:\Users\lin\stable-diffusion-webui-amdgpu-forge\repositories\BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (30/30), done.
Receiving objects: 100% (277/277), 7.03 MiB | 2.01 MiB/s, done.
remote: Total 277 (delta 137), reused 136 (delta 135), pack-reused 112
Resolving deltas: 100% (152/152), done.
Traceback (most recent call last):
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\launch.py", line 51, in <module>
    main()
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\launch.py", line 39, in main
    prepare_environment()
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 600, in prepare_environment
    from modules import devices
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\modules\devices.py", line 3, in <module>
    import ldm_patched.modules.model_management as model_management
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\ldm_patched\modules\model_management.py", line 122, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\ldm_patched\modules\model_management.py", line 91, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "D:\Users\lin\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "D:\Users\lin\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
請按任意鍵繼續 . . .

### Steps to reproduce the problem

1. git clone
2. set file
3. open it 

### What should have happened?

install it 

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

none

### Console logs

```Shell
as above
```

### Additional information

first time use it

**Comment by brknsoul** [comment]
Try again, following this guide; 
https://github.com/brknsoul/ROCmLibs/wiki/Installing-Forge%E2%80%90Zluda

**Comment by waldolin** [comment]
> Try again, following this guide; https://github.com/brknsoul/ROCmLibs/wiki/Installing-Forge%E2%80%90Zluda

i follow this guide but not success
the information as following.
---
'--ckpt-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--hypernetwork-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--embeddings-dir' 不是內部或外部命令、可執行的程式或批次檔。
'--lora-dir' 不是內部或外部命令、可執行的程式或批次檔。
'et' 不是內部或外部命令、可執行的程式或批次檔。
venv "D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-1.7.0
Commit hash: e45bfd91b123559e69b5bfca3824df15735a0b95
Using ZLUDA in D:\Users\lin\stable-diffusion-webui-amdgpu-forge\.zluda
Total VRAM 49136 MB, total RAM 130883 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon PRO W7900 [ZLUDA] : native
VAE dtype: torch.bfloat16
Launching Web UI with arguments: --zluda --theme dark --skip-torch-cuda-test --use-directml --medvram --precision full --no-half --no-half-vae --opt-sub-quad-attention --enable-insecure-extension-access --deepdanbooru --disable-nan-check
Arg --medvram is removed in Forge.
Now memory management is fully automatic and you do not need any command flags.
Please just remove this flag.
In extreme cases, if you want to force previous lowvram/medvram behaviors, please use --always-offload-from-vram
CUDA Stream Activated:  False

------------------------------------------------------------------------------------------------------------------------
launch.py 51 <module>
main()

launch.py 47 main
start()

launch_utils.py 651 start
import webui

webui.py 19 <module>
initialize.imports()

initialize.py 35 imports
import gradio  # noqa: F401

__init__.py 3 <module>
import gradio.components as components

__init__.py 1 <module>
from gradio.components.annotated_image import AnnotatedImage

annotated_image.py 13 <module>
from gradio.components.base import IOComponent, _Keywords

base.py 20 <module>
from fastapi import UploadFile

__init__.py 7 <module>
from .applications import FastAPI as FastAPI

applications.py 15 <module>
from fastapi import routing

routing.py 22 <module>
from fastapi import params

params.py 4 <module>
from pydantic.fields import FieldInfo, Undefined

ImportError:
cannot import name 'Undefined' from 'pydantic.fields' (D:\Users\lin\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\pydantic\fields.py)
請按任意鍵繼續 . . .

**Comment by brknsoul** [comment]
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/2#issuecomment-2102516603

**Comment by waldolin** [comment]
> [#2（評論）](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/2#issuecomment-2102516603)

it works!! thank you a millions!!
