### ISSUE TITLE
launch.py: error: unrecognized arguments: --use-zluda

### ISSUE THREAD

**Issue by schlosrat** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#55]
With Git-2.47.0.2-64-bit, ROCM 6 and Python 3.10.6 installed previously from a working stable-diffusion-webui-directml install
using Zluda v3.8.4 (ZLUDA-windows-rocm6-amd64)
1. Installed via git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git
2. ran webui-user.bat and got GUI in web browser
3. Closed GUI
4. copied cublas.dll from Zluda v3.8.4 to cublas64_12.dll in F:\stable-diffusion-webui-forge\venv\Lib\site-packages\torch
5. copied cusparde.dll from Zluda v3.8.4 to cusparde64_12.dll in F:\stable-diffusion-webui-forge\venv\Lib\site-packages\torch
6. ran webui.bat --use-zluda
This produced the error noted in the issue title.

What am I doing wrong here? I was able to get both stable-diffusion-webui-amdgpu and stable-diffusion-webui-directml to work with this process, but for some reason, stable-diffusion-webui-forge doesn't like the --use-zluda command line argument.

**Comment by lshqqytiger** [comment]
You should clone `https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge.git`, not `https://github.com/lllyasviel/stable-diffusion-webui-forge.git`.
