### ISSUE TITLE
[BUG]/[Function loss] --use-directml

### ISSUE THREAD

**Issue by BrickDesignerNL** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#61]
In the https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu there is a feature called --use-directml 
I see that it's not in the repo, is that intended?

And if so, how can I make sure it will utilize my GPU/NPU on my Qualcomm X Elite (ARM64).

Thank you.

**Comment by TheFerumn** [comment]
First of all you talking about this : https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu
OR this: https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge
??
Anyway both of them should work. You just need to edit your webui-user.bat and add `--use-directml` or `--directml` after `set COMMANDLINE_ARGS=`  but i am not sure if its compatible with ARM64 devices

**Comment by BrickDesignerNL** [comment]
Ah, thanks, then I'll ignore trying to use directml.

Hope a WebGPU version might work one day 😉

**Comment by TheFerumn** [comment]
> The non-forge version has the `--use-directml` option, the forge edition is missing it.
> 

No. I used --directml on Forge. It works same way as --use-directml in non-Forge. Honestly i lost a track which command you should use in which version but both of them do exactly the same.

> Thanks, now knowing direcml is cpu only, I'll ignore trying to use directml.
> 
> Hope a WebGPU version might work one day 😉

DirectML is not CPU only. Its used mainly for AMD GPUs and Intel APUs. You have something different and there is not full support yet but i just checked it quickly so don't take this as 100% info.
