### ISSUE TITLE
Cannot install requirement torch

### ISSUE THREAD

**Issue by mansman12** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#63]
Get this error during first install:

`Installing torch and torchvision
Looking in indexes: https://download.pytorch.org/whl/nightly/rocm5.7
Collecting torch
  ERROR: HTTP error 403 while getting https://download.pytorch.org/whl/nightly/rocm5.7/torch-2.2.0.dev20231010%2Brocm5.7-cp310-cp310-linux_x86_64.whl (from https://download.pytorch.org/whl/nightly/rocm5.7/torch/)
ERROR: Could not install requirement torch from https://download.pytorch.org/whl/nightly/rocm5.7/torch-2.2.0.dev20231010%2Brocm5.7-cp310-cp310-linux_x86_64.whl because of HTTP error 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/nightly/rocm5.7/torch-2.2.0.dev20231010%2Brocm5.7-cp310-cp310-linux_x86_64.whl for URL https://download.pytorch.org/whl/nightly/rocm5.7/torch-2.2.0.dev20231010%2Brocm5.7-cp310-cp310-linux_x86_64.whl (from https://download.pytorch.org/whl/nightly/rocm5.7/torch/)
`

On Linux, have been able to use different versions of SD fine (A1111, webui-forge, webui-reForge) and swap between them using Git. Only have this issue with webui-amdgpu-forge.

**Comment by TheFerumn** [comment]
Well, I can confirm there is forbidden access to download this version of torch from the pytorch.org. I guess you have to install torch manually. Maybe some of your other forks have same version to just copy it ?

**Comment by mansman12** [comment]
Figured out how to install it, it's an issue with pytorch moving their nightly builds link but should also be updated in the way the virtual environment searches for the packages.

To solve you need to do the following:

- Go to https://download.pytorch.org/whl
- Download the following wheels: torchvision, pytorch-triton-rocm and torch
- Want the versions that have both rocm5.7 and cp310 in them
- For torchvision I found that only the 17.0 version worked (rather than the 18.0+ version) as others installed a newer version of torch that wasn't compatible
- Once downloaded manually install them in the virtual environment in the following order: torchvision, pytorch-triton then torch
- If you install them not in that order they end up conflicting/downloading the wrong version and the webui script won't work
