### ISSUE TITLE
[Feature Request]: Hope the author can provide an installation tutorial for ROCm 6.1.2 Version!

### ISSUE THREAD

**Issue by bigwinboy** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

OS: Windows 11/AMD 7900XTX
ROCm: 6.1.2
Zluda: 3.8.1
The installation prompt will show missing files (ROCm 5.7.1 will not have this error prompt), and although you can enter the UI without any problem, it will fail to load the model, so I hope the author can update the installation step-by-step instructions for ROCm 6.1.2 version, thanks!

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by lshqqytiger** [comment]
ROCm 6 is now supported.
